title: Xiangnan Li
author: Xiangnan Li
email: xiangnanli1123@outlook.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to the personal homepage of Xiangnan Li!

# Social links
# github_username:  your-github-username
# linkedin_username: your-linkedin-username
# twitter_username: your-twitter-username

# Build settings
theme: minima # Or whatever theme you are using
plugins:
  - jekyll-feed